In [1]:
import sys
sys.path.append('../..')
from pkg.orbital_congestion import socrates

socrates_files_path = '../../data/socrates/'
tle_file_path = '../../data/socrates_tca_gp_history_tle.pkl.gz'

In [2]:
full_soc_df = socrates.get_all_socrates_data(socrates_files_path)

100%|██████████████████████████████████████████████████████████████████████████████████| 77/77 [00:06<00:00, 11.10it/s]

In [3]:
full_soc_df[full_soc_df['sat_pair'].str.contains('STARLINK-1694') & full_soc_df['sat_pair'].str.contains('COSMOS 2251')]

,sat1_norad,sat1_name,sat1_days_epoch,max_prob,dil_thr_km,min_rng_km,rel_velo_kms,sat2_norad,sat2_name,sat2_days_epoch,start_time,tca_time,stop_time,extract_sort,extract_date,sat1_last_epoch,sat2_last_epoch,sat_pair
1,46544,STARLINK-1694 [+],0 days 22:32:09.600000,0.133100,0.002,0.004,13.574,37521,COSMOS 2251 DEB [-],8 days 00:47:31.200000,2021-01-05 20:32:05.582,2021-01-05 20:32:05.950,2021-01-05 20:32:06.319,MAXPROB,2021-01-05 08:30:04.051446,2021-01-04 21:59:56.350,2020-12-28 19:44:34.750,STARLINK-1694 [+]-COSMOS 2251 DEB [-]
1001,46544,STARLINK-1694 [+],0 days 22:32:09.600000,0.133100,0.002,0.004,13.574,37521,COSMOS 2251 DEB [-],8 days 00:47:31.200000,2021-01-05 20:32:05.582,2021-01-05 20:32:05.950,2021-01-05 20:32:06.319,MINRANGE,2021-01-05 08:30:04.051446,2021-01-04 21:59:56.350,2020-12-28 19:44:34.750,STARLINK-1694 [+]-COSMOS 2251 DEB [-]
953,46544,STARLINK-1694 [+],0 days 15:37:26.400000,0.000012,0.156,0.537,9.392,36042,COSMOS 2251 DEB [-],2 days 11:12:28.800000,2021-01-07 21:37:00.885,2021-01-07 21:37:01.414,2021-01-07 21:37:01.944,MAXPROB,2021-01-07 20:30:04.203946,2021-01-07 05:59:35.014,2021-01-05 10:24:32.614,STARLINK-1694 [+]-COSMOS 2251 DEB [-]
1503,46544,STARLINK-1694 [+],0 days 15:37:26.400000,0.000012,0.156,0.537,9.392,36042,COSMOS 2251 DEB [-],2 days 11:12:28.800000,2021-01-07 21:37:00.885,2021-01-07 21:37:01.414,2021-01-07 21:37:01.944,MINRANGE,2021-01-07 20:30:04.203946,2021-01-07 05:59:35.014,2021-01-05 10:24:32.614,STARLINK-1694 [+]-COSMOS 2251 DEB [-]

In [4]:
min_soc_df, tle_df = socrates.get_all_socrates_and_tle_data(socrates_files_path, tle_file_path)

100%|██████████████████████████████████████████████████████████████████████████████████| 77/77 [00:06<00:00, 11.19it/s]

In [7]:
tle_df[tle_df['sat_pair'].str.contains('STARLINK-1694') & tle_df['sat_pair'].str.contains('COSMOS 2251')]

,sat1_norad,sat1_name,sat1_days_epoch,max_prob,dil_thr_km,min_rng_km,rel_velo_kms,sat2_norad,sat2_name,sat2_days_epoch,...,extract_sort,extract_date,sat1_last_epoch,sat2_last_epoch,sat_pair,group,sat1_tle,sat1_tle_epoch,sat2_tle,sat2_tle_epoch
95296,46544,STARLINK-1694 [+],0 days 22:32:09.600000,0.133100,0.002,0.004,13.574,37521,COSMOS 2251 DEB [-],8 days 00:47:31.200000,...,MAXPROB,2021-01-05 08:30:04.051446,2021-01-04 21:59:56.350,2020-12-28 19:44:34.750,STARLINK-1694 [+]-COSMOS 2251 DEB [-],95297,1 46544U 20070N 21004.91667824 -.01123657 0...,2021-01-04T22:00:00.999936,1 37521U 93036BNA 20363.82305027 .00003519 0...,2020-12-28T19:45:11.543328
95297,46544,STARLINK-1694 [+],0 days 15:37:26.400000,0.000012,0.156,0.537,9.392,36042,COSMOS 2251 DEB [-],2 days 11:12:28.800000,...,MAXPROB,2021-01-07 20:30:04.203946,2021-01-07 05:59:35.014,2021-01-05 10:24:32.614,STARLINK-1694 [+]-COSMOS 2251 DEB [-],95298,1 46544U 20070N 21007.25001157 -.00010068 0...,2021-01-07T06:00:00.999648,1 36042U 93036AXD 21005.43327230 .00004508 0...,2021-01-05T10:23:54.726720